# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-18 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

forward_create_tables = """
    CREATE TABLE compute_server (
        id serial NOT NULL PRIMARY KEY,
        name text NOT NULL,
        address text NOT NULL,
        editor_id integer NOT NULL,
        edition_time timestamp with time zone DEFAULT now() NOT NULL,
        environment_source_path text,
        diluvian_path text,
        results_directory text
    );

    -- Create history tables
    SELECT create_history_table('compute_server'::regclass, 'edition_time', 'txid');
"""

backward_create_tables = """
    SELECT disable_history_tracking_for_table('compute_server'::regclass,
        get_history_table_name('compute_server'::regclass));
    SELECT drop_history_table('compute_server'::regclass);

    DROP TABLE compute_server CASCADE;
"""


class Migration(migrations.Migration):

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.RunSQL(
            forward_create_tables,
            backward_create_tables,
            [
                migrations.CreateModel(
                    name="ComputeServer",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "edition_time",
                            models.DateTimeField(default=django.utils.timezone.now),
                        ),
                        ("name", models.TextField()),
                        ("address", models.TextField()),
                        (
                            "editor",
                            models.ForeignKey(
                                db_column="editor_id",
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="compute_server_editor",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        ("diluvian_path", models.TextField()),
                        ("results_directory", models.TextField()),
                        ("model_source_path", models.TextField()),
                    ],
                    options={"db_table": "compute_server"},
                )
            ],
        )
    ]
