# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-18 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

forward_create_tables = """
    CREATE TABLE autoproofreader_proofreadtreenodes (
        id serial NOT NULL PRIMARY KEY,
        node_id integer NOT NULL,
        parent_id integer,
        result_id integer NOT NULL,
        x float NOT NULL,
        y float NOT NULL,
        z float NOT NULL,
        branch_score float NOT NULL,
        branch_dx float NOT NULL,
        branch_dy float NOT NULL,
        branch_dz float NOT NULL,
        connectivity_score float NOT NULL,
        reviewed boolean DEFAULT false,
        txid serial,
        editor_id integer NOT NULL,
        edition_time timestamp with time zone DEFAULT now() NOT NULL,
        creation_time timestamp with time zone DEFAULT now() NOT NULL,
        user_id integer NOT NULL,
        project_id integer NOT NULL
    );

    -- Create history tables
    SELECT create_history_table('autoproofreader_proofreadtreenodes'::regclass, 'edition_time', 'txid');
"""

backward_create_tables = """
    SELECT disable_history_tracking_for_table('autoproofreader_proofreadtreenodes'::regclass,
        get_history_table_name('autoproofreader_proofreadtreenodes'::regclass));
    SELECT drop_history_table('autoproofreader_proofreadtreenodes'::regclass);

    DROP TABLE autoproofreader_proofreadtreenodes CASCADE;
"""


class Migration(migrations.Migration):

    dependencies = [("autoproofreader", "0001_initial")]

    operations = [
        migrations.RunSQL(
            forward_create_tables,
            backward_create_tables,
            [
                migrations.CreateModel(
                    name="ProofreadTreeNodes",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("node_id", models.IntegerField()),
                        ("parent_id", models.IntegerField()),
                        ("x", models.FloatField()),
                        ("y", models.FloatField()),
                        ("z", models.FloatField()),
                        ("branch_score", models.FloatField()),
                        ("branch_dx", models.FloatField()),
                        ("branch_dy", models.FloatField()),
                        ("branch_dz", models.FloatField()),
                        ("connectivity_score", models.FloatField()),
                        ("reviewed", models.BooleanField(default=False)),
                        (
                            "result",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="autoproofreader.AutoproofreaderResult",
                            ),
                        ),
                        (
                            "creation_time",
                            models.DateTimeField(default=django.utils.timezone.now),
                        ),
                        (
                            "edition_time",
                            models.DateTimeField(default=django.utils.timezone.now),
                        ),
                        ("config", models.TextField()),
                        (
                            "project",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="catmaid.Project",
                            ),
                        ),
                        (
                            "user",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "editor",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                )
            ],
        )
    ]
