# Generated by Django 2.1.3 on 2019-05-16 21:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("autoproofreader", "0002_add_proofread_tree_nodes_table")]

    operations = [
        migrations.RemoveField(model_name="computeserver", name="edition_time"),
        migrations.RemoveField(model_name="computeserver", name="editor"),
        migrations.AddField(
            model_name="computeserver",
            name="project_whitelist",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(blank=True, null=True),
                null=True,
                size=None,
            ),
        ),
    ]
