dist: xenial
sudo: required
notifications:
  email: false
language: python
cache: pip
python:
  - "3.6"
global:
  - CATMAID_DIR=$TRAVIS_BUILD_DIR/travis/CATMAID
  - PACKAGE_DIR=$TRAVIS_BUILD_DIR/floodfilling
  - JS_DIR=$PACKAGE_DIR/static/floodfilling/js
env:
  - CATMAID_BRANCH=master
  - CATMAID_BRANCH=dev
matrix:
  fast_finish: true
  allow_failures:
    - env: CATMAID_BRANCH=dev
addons:
  postgresql: 10
before_install:
  - echo $CATMAID_DIR
  - travis_retry sudo apt-get update -y -qq
  # setup CATMAID
  - git clone -b $CATMAID_BRANCH https://github.com/catmaid/CATMAID.git $CATMAID_DIR
  - cd $CATMAID_DIR
  - bash scripts/travis/install_postgres.sh
  - bash scripts/travis/install_python.sh
  - nvm install 11
install:
  - cd $CATMAID_DIR
  - bash scripts/travis/install_requirements.sh
  - pip install coveralls flake8
  - npm install 11
  # install extension
  - pip install -e $TRAVIS_BUILD_DIR
before_script:
  - cd $CATMAID_DIR
  # This solves the issue of no file "/usr/share/postgresql/10/extension/postgis.control"
  # However this line is also in the install_postgres.sh file on line 21, so I'm not sure why this is needed
  - sudo apt install postgresql-10-postgis-2.4-scripts
  - bash scripts/travis/setup_database.sh
  - bash $TRAVIS_BUILD_DIR/scripts/travis/configure_catmaid.sh

script:
  - cd $CATMAID_DIR/django/projects
  - python manage.py migrate --noinput
  - python manage.py collectstatic --link --noinput
  - coverage run --source=floodfilling manage.py test floodfilling.tests
  - flake8 --config=$CATMAID_DIR/.travis.flake8 --statistics --count --exit-zero -q -q $PACKAGE_DIR
  - jshint --config=$CATMAID_DIR/.travis.jshintrc --exclude-path=$CATMAID_DIR/.travis.jshintignore $JS_DIR
after_success:
  - coveralls
