dist: xenial
sudo: required
language: python
cache: pip
python:
  - "3.6"
env:
  - CATMAID_DIR=$TRAVIS_BUILD_DIR/travis/CATMAID CATMAID_BRANCH=master
  - CATMAID_DIR=$TRAVIS_BUILD_DIR/travis/CATMAID CATMAID_BRANCH=dev
matrix:
  fast_finish: true
  allow_failures:
    - env: CATMAID_DIR=$TRAVIS_BUILD_DIR/travis/CATMAID CATMAID_BRANCH=dev
addons:
  postgresql: 10  # will be replaced by v10, travis doesn't have it yet
before_install:
  - travis_retry sudo apt-get update -y -qq
  # setup CATMAID
  - git clone -b $CATMAID_BRANCH https://github.com/catmaid/CATMAID.git $CATMAID_DIR
  - cd $CATMAID_DIR
  - bash scripts/travis/install_postgres.sh
  - bash scripts/travis/install_python.sh
  - nvm install 11
install:
  - cd $CATMAID_DIR
  - bash scripts/travis/install_requirements.sh
  - pip install -e $TRAVIS_BUILD_DIR
  - cd django/projects
  - pip install coveralls flake8
  - npm install
  - export PATH=$(npm bin):$PATH
before_script:
  - cd $CATMAID_DIR
  # This solves the issue of no file "/usr/share/postgresql/10/extension/postgis.control"
  # However this line is also in the install_postgres.sh file on line 21, so I'm not sure why this is needed
  - sudo apt install postgresql-10-postgis-2.4-scripts
  - bash scripts/travis/setup_database.sh
  - bash $TRAVIS_BUILD_DIR/scripts/travis/configure_catmaid.sh

script:
  - cd $CATMAID_DIR/django/projects
  - python manage.py migrate --noinput
  - python manage.py collectstatic --link --noinput
  - coverage run --source=autoproofreader manage.py test autoproofreader.tests
  - cd $TRAVIS_BUILD_DIR
  - flake8 --config .travis.flake8 --exclude=$CATMAID_DIR .
  - jshint --config .travis.jshintrc --exclude=$CATMAID_DIR .
after_success:
  - coveralls

